import type { Item } from '@infinity-realms/shared/types';

export const ITEM_CATALOG: Record<string, Item> = {
  // Consumables
  'health-potion-1': {
    id: 'health-potion-1',
    name: 'Minor Health Potion',
    type: 'consumable',
    rarity: 'common',
    value: 10,
    icon: '🧪',
    description: 'Restores 50 HP.',
  },

  // Seeds & Crops
  'magic-seed': {
    id: 'magic-seed',
    name: 'Leyline Seed',
    type: 'seed',
    rarity: 'uncommon',
    icon: '🌱',
    value: 5,
    description: 'Plant on dirt to grow crops.',
  },
  'crop-plains': {
    id: 'crop-plains',
    name: 'Sunwheat',
    description: 'Golden wheat infused with plains energy.',
    type: 'crop',
    rarity: 'common',
    icon: '🌾',
    value: 8,
  },
  'crop-forest': {
    id: 'crop-forest',
    name: 'Lifebloom',
    description: 'A glowing flower from the deep forest.',
    type: 'crop',
    rarity: 'uncommon',
    icon: '🌸',
    value: 12,
  },
  'crop-desert': {
    id: 'crop-desert',
    name: 'Cactus Fruit',
    description: 'A juicy fruit bursting with water magic.',
    type: 'crop',
    rarity: 'common',
    icon: '🌵',
    value: 10,
  },
  'crop-snow': {
    id: 'crop-snow',
    name: 'Frostberry',
    description: 'An icy berry that chills the touch.',
    type: 'crop',
    rarity: 'uncommon',
    icon: '🫐',
    value: 15,
  },
  'crop-volcano': {
    id: 'crop-volcano',
    name: 'Emberbloom',
    description: 'A fiery flower that is warm to the touch.',
    type: 'crop',
    rarity: 'rare',
    icon: '🌺',
    value: 25,
  },
  'crop-swamp': {
    id: 'crop-swamp',
    name: 'Poisoncap',
    description: 'A toxic mushroom infused with decay.',
    type: 'crop',
    rarity: 'common',
    icon: '🍄',
    value: 8,
  },

  // Materials
  'iron-ore': {
    id: 'iron-ore',
    name: 'Iron Ore',
    type: 'material',
    rarity: 'common',
    icon: '🪨',
    value: 10,
    description: 'Raw iron ore.',
  },
  'herbals': {
    id: 'herbals',
    name: 'Mystic Herbs',
    type: 'material',
    rarity: 'uncommon',
    icon: '🌿',
    value: 12,
    description: 'Potent herbs used in alchemy.',
  },
  'sand-glass': {
    id: 'sand-glass',
    name: 'Sand Glass',
    type: 'material',
    rarity: 'common',
    icon: '⌛',
    value: 8,
    description: 'Silica sand used in glassmaking.',
  },
  'ice-crystal': {
    id: 'ice-crystal',
    name: 'Ice Crystal',
    type: 'material',
    rarity: 'uncommon',
    icon: '❄️',
    value: 15,
    description: 'Frozen water that never melts.',
  },
  'leyline-essence': {
    id: 'leyline-essence',
    name: 'Leyline Essence',
    description: 'Raw magical energy harvested from active world leylines.',
    type: 'material',
    rarity: 'rare',
    icon: '⚡',
    value: 10,
  },

  // Equipment
  'iron-sword': {
    id: 'iron-sword',
    name: 'Iron Sword',
    type: 'weapon',
    rarity: 'common',
    value: 50,
    icon: '🗡️',
    description: 'A basic iron sword.',
    stats: { attack: 5 },
  },
  'steel-sword': {
    id: 'steel-sword',
    name: 'Steel Sword',
    type: 'weapon',
    rarity: 'uncommon',
    value: 120,
    icon: '⚔️',
    description: 'A well-forged steel blade.',
    stats: { attack: 8 },
  },
  'flame-blade': {
    id: 'flame-blade',
    name: 'Flame Blade',
    type: 'weapon',
    rarity: 'rare',
    value: 250,
    icon: '🔥',
    description: 'A sword wreathed in eternal flame.',
    stats: { attack: 14, luck: 2 },
  },
  'leather-armor': {
    id: 'leather-armor',
    name: 'Leather Armor',
    type: 'armor',
    rarity: 'common',
    value: 40,
    icon: '🛡️',
    description: 'Basic leather protection.',
    stats: { defense: 3, maxHp: 15 },
  },
  'chain-mail': {
    id: 'chain-mail',
    name: 'Chain Mail',
    type: 'armor',
    rarity: 'uncommon',
    value: 100,
    icon: '🛡️',
    description: 'Interlocking metal rings.',
    stats: { defense: 6, maxHp: 30 },
  },
  'iron-helmet': {
    id: 'iron-helmet',
    name: 'Iron Helmet',
    type: 'helmet',
    rarity: 'common',
    value: 30,
    icon: '🪖',
    description: 'Sturdy head protection.',
    stats: { defense: 2, maxHp: 10 },
  },
  'lucky-ring': {
    id: 'lucky-ring',
    name: 'Lucky Ring',
    type: 'accessory',
    rarity: 'rare',
    value: 200,
    icon: '💍',
    description: 'Fortune favors the wearer.',
    stats: { luck: 5, speed: 10 },
  },
};
