FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY shared/package*.json ./shared/
COPY ai/package*.json ./ai/
COPY server/package*.json ./server/
RUN npm install
COPY . .
RUN npm run build --workspace=shared && npm run build --workspace=ai && npm run build --workspace=server

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
COPY server/package*.json ./server/
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/shared/dist ./shared/dist
COPY --from=builder /app/ai/dist ./ai/dist
COPY --from=builder /app/server/dist ./server/dist
COPY --from=builder /app/server/prisma ./server/prisma

EXPOSE 3001
CMD ["node", "server/dist/main"]
